apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: tomcat-service
  name: tomcat-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      api: tomcat-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        api: tomcat-service
    spec:
      containers:
        - image: tomcat:8.5.69
          name: tomcat-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: netology-ml
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    api: tomcat-service
  type: NodePort

