stages:
  - build
  - test
building:
  tags:
    - netology
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch info.txt
testing:
  tags:
    - netology
  stage: test
  script:
    - echo "Testing"
    - if [ -f info.txt ]; then echo "File info.txt exists"; else echo "File info.txt doesn't exits"; fi